if (self.CavalryLogger) { CavalryLogger.start_js(["oSl9qcH"]); }

__d("CometSinglePageChannelTabRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3830897980352647",metadata:{},name:"CometSinglePageChannelTabRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeFeedRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"5712539672120647",metadata:{},name:"CometVideoHomeFeedRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomePlaylistRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"5533786173360508",metadata:{},name:"CometVideoHomePlaylistRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeRootProviderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2939812456104778",metadata:{},name:"CometVideoHomeRootProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3707683145972691",metadata:{},name:"CometVideoHomeStickyHeaderWatchlistMenuRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeLeftRailWatchlistQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4278020058898065",metadata:{},name:"CometVideoHomeLeftRailWatchlistQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometSinglePageChannelTabRoot.entrypoint",["CometSinglePageChannelTabRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometSinglePageRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometSinglePageRoute.entrypoint")(b("JSResourceForInteraction")("CometSinglePageChannelTabRoot.react").__setRef("CometSinglePageChannelTabRoot.entrypoint"),function(a){a=a.routeProps.pageID;return{queries:{singlePageChannelTabRootQueryReference:{parameters:b("CometSinglePageChannelTabRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CometSinglePageChannelTabRoot",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedLocation:"PAGE_TIMELINE",feedbackSource:72,focusCommentID:null,pageID:a,scale:b("WebPixelRatio").get()*4,useDefaultActor:!1}}}}});e.exports=a}),null);
__d("CometVideoHomeFeedEntryPointVariables",["CometVideoHomeCommonEntryPointVariables"],(function(a,b,c,d,e,f){"use strict";a=babelHelpers["extends"]({},b("CometVideoHomeCommonEntryPointVariables"),{UFI2CommentsProvider_commentsKey:"CometVideoHomeFeedRootQuery",triggerData:{injected_video_id:null}});e.exports=a}),null);
__d("buildCometVideoHomeRouteForResource.entrypoint",["CometVideoHomeLeftRailWatchlistQuery$Parameters","CometVideoHomeRootProviderQuery$Parameters","CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters","WebPixelRatio","cr:1714517","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f){"use strict";e.exports=a;b("cr:1714517");function a(a){return b("createContentAreaCompoundEntryPointBuilder")(a,function(a){return{rootProviderQueryReference:{parameters:b("CometVideoHomeRootProviderQuery$Parameters"),variables:{}},stickyHeaderWatchlistQueryReference:{parameters:b("CometVideoHomeStickyHeaderWatchlistMenuRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}},watchlistSettingsQueryReference:{parameters:b("CometVideoHomeLeftRailWatchlistQuery$Parameters"),variables:{scale:b("WebPixelRatio").get()}}}})}}),null);
__d("buildCometVideoHomeRoute.entrypoint",["JSResourceForInteraction","buildCometVideoHomeRouteForResource.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRouteForResource.entrypoint")(b("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("buildCometVideoHomeRoute.entrypoint"));e.exports=a}),null);
__d("CometVideoHomeFeedRoot.entrypoint",["CometVideoHomeFeedEntryPointVariables","CometVideoHomeFeedRootQuery$Parameters","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint","cr:1714516"],(function(a,b,c,d,e,f){"use strict";b("cr:1714516");a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResourceForInteraction")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRoot.entrypoint"),function(a){return{queries:{feedRootQueryReference:{options:{fetchPolicy:"network-only"},parameters:b("CometVideoHomeFeedRootQuery$Parameters"),variables:b("CometVideoHomeFeedEntryPointVariables")}}}});e.exports=a}),null);
__d("CometVideoHomeFeedRootBEOneAhead",["JSResourceForInteraction"],(function(a,b,c,d,e,f){"use strict";b("JSResourceForInteraction")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRootBEOneAhead");a=null;e.exports=a}),null);
__d("CometVideoHomeFeedRootEntrypoint.entrypoint",["CometVideoHomeFeedEntryPointVariables","CometVideoHomeFeedRootQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f){"use strict";var g=0,h=function(){return++g};a={getPreloadProps:function(a){return{queries:{feedRootQueryReference:{options:{fetchKey:h(),fetchPolicy:"network-only"},parameters:b("CometVideoHomeFeedRootQuery$Parameters"),variables:babelHelpers["extends"]({},b("CometVideoHomeFeedEntryPointVariables"),{triggerData:{injected_video_id:a.routeProps.v}})}}}},root:b("JSResourceForInteraction")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRootEntrypoint.entrypoint")};e.exports=a}),null);
__d("CometVideoHomePlaylistRoot.entrypoint",["CometVideoHomePlaylistRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResourceForInteraction")("CometVideoHomePlaylistRoot.react").__setRef("CometVideoHomePlaylistRoot.entrypoint"),function(a){a={id:a.routeProps.id};return{queries:{playlistRootQueryReference:{parameters:b("CometVideoHomePlaylistRootQuery$Parameters"),variables:{scale:b("WebPixelRatio").get(),trigger_data:a}}}}});e.exports=a}),null);
__d("CometVideoHomeRootBEOneAhead",["JSResourceForInteraction"],(function(a,b,c,d,e,f){"use strict";b("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("CometVideoHomeRootBEOneAhead");a=null;e.exports=a}),null);
__d("CometVideoHomeLanceletRoot.entrypoint",["CometSinglePageChannelTabRoot.entrypoint","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometVideoHomeRoute.entrypoint")(b("JSResourceForInteraction")("CometVideoHomeLanceletRoot.react").__setRef("CometVideoHomeLanceletRoot.entrypoint"),function(a){return{entryPoints:{pageEntryPoint:{entryPoint:b("CometSinglePageChannelTabRoot.entrypoint"),entryPointParams:a}},extraProps:a}});e.exports=a}),null);